title: Visually Grounded Interaction and Language (ViGIL) 4.0
description: Visually Grounded Interaction and Language (ViGIL) 4.0 Workshop
  ---
baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
include: ['_pages']
ga_id: UA-144588579-1
